#!/bin/bash

# SLURM script to test parallel Meep with Slurm solving fields for a straight waveguide as in Meep's Tutorial.

#SBATCH --ntasks=8                # Total number of cores

#SBATCH --nodes=1                 # Total number of nodes

#SBATCH -p free-rider             # Partition

#SBATCH -t 10                     # Maximum time reserved for execution, expressed in minutes

#SBATCH --job-name=meep-tut                  # Task name

#SBATCH --output="ErrorLogs/meep-tut-%j.out" # Output file

#SBATCH --error="ErrorLogs/meep-tut-%j.err"  # Error file

# #SBATCH --test-only   # Check if legible and return posible start time

# ## Environment!
export PATH=/nfs/home/vpais/miniconda/bin:$PATH
conda init bash
source ~/.bash_profile
source ~/.bashrc
conda activate pmp
cd /nfs/home/vpais/NanoMeepPlasmonics

# ## Parallel way 1 >> Job 380822

# srun python -m mpi4py ./MeepTutorial/straight-waveguide.py

# ## Parallel way 2 >> Job 380824

# Generate Machinefile for mpi such that hosts are in the same order as if run via srun
# MACHINEFILE="SlurmScripts/ConfigFiles/nodes.$SLURM_JOB_ID"
# srun -l /bin/hostname | sort -n | awk '{print $2}' > $MACHINEFILE

# Run using generated Machine file:
# mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE ./MeepTutorial/straight-waveguide.py

# ## Parallel way 3 >> Job 380830

# srun -n $SLURM_NTASKS python -m mpi4py ./MeepTutorial/straight-waveguide.py

# ## Parallel way 4 >> Job 380833

# mpirun -np $SLURM_NTASKS python -m mpi4py ./MeepTutorial/straight-waveguide.py

# ## Parallel way 5 >> Job 380867

# mpirun -np $SLURM_NTASKS -mca plm rsh python -m mpi4py ./MeepTutorial/straight-waveguide.py

# ## Parallel way 6 >> Job 381006 >> THIS WORKSSSSS! >> But Job 381028 >> IT'S BROKEN NOW :S

srun -n $SLURM_NTASKS --mpi=pmi2 python -m mpi4py ./MeepTutorial/straight-waveguide.py

# ## Parallel way 7 >> Job 381010

# alias tupacrun='srun -n $SLURM_NTASKS --mpi=pmi2 python -m mpi4py'
# tupacrun ./MeepTutorial/straight-waveguide.py

# ## Parallel way 8 >> Untested

# mpirun -np $SLURM_NTASKS -mca rmaps seq python -m mpi4py ./MeepTutorial/straight-waveguide.py

# ## Parallel way 9 >> Untested

# Generate Machinefile for mpi such that hosts are in the same order as if run via srun
# MACHINEFILE="SlurmScripts/ConfigFiles/nodes.$SLURM_JOB_ID"
# srun -l /bin/hostname | sort -n | awk '{print $2}' > $MACHINEFILE

# Run using generated Machine file:
# mpirun -np $SLURM_NTASKS -mca rmaps seq -machinefile $MACHINEFILE python -m mpi4py ./MeepTutorial/straight-waveguide.py
