#mpirun --use-hwthread-cpus -np 6 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 6 --parallel True -res 2 --from-um-factor 10e-3 -s "FluxR0.30Res2" -f "AuMieMediums/AllWaterTest/9)BoxDimensions/FluxR" -r 51.5 -pp "R" --wlen-range "np.array([500,650])" --index 1.33 --flux-r-factor 0.3
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 6 --parallel True -res 2 --from-um-factor 10e-3 -s "AirR06.5Res2" -f "AuMieMediums/AllWaterTest/9)BoxDimensions/AirR" -r 51.5 -pp "R" --wlen-range "np.array([500,650])" --index 1.33 --air-r-factor 6.5
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 6 --parallel True -res 2 --from-um-factor 10e-3 -s "PMLWlen0.95Res2" -f "AuMieMediums/AllWaterTest/9)BoxDimensions/PMLWlen" -r 51.5 -pp "R" --wlen-range "np.array([500,650])" --index 1.33 -pml 0.95
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 6 --parallel True -res 2 --from-um-factor 10e-3 -s "WLenMax700Res2" -f "AuMieMediums/AllWaterTest/9)BoxDimensions/WLenMax" -r 51.5 -pp "R" --wlen-range "np.array([500,700])" --index 1.33
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 6 --parallel True -res 2 --from-um-factor 10e-3 -s "WLenMin500Res2" -f "AuMieMediums/AllWaterTest/9)BoxDimensions/WLenMin" -r 51.5 -pp "R" --wlen-range "np.array([500,650])" --index 1.33
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 6 --parallel True -res 2 --from-um-factor 10e-3 -s "TFCell0.2Res2" -f "AuMieSphere/AuMie/13)TestPaper/4)PaperJCFit/TestTFCell/AllVac450650" -r 51.5 -pp "JC" --wlen-range "np.array([450,650])" --time-factor-cell 0.2
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 6 --parallel True -res 2 --from-um-factor 10e-3 -s "STFactor01.0Res2" -f "AuMieSphere/AuMie/13)TestPaper/4)PaperJCFit/TestSTFactor/AllVac450650" -r 51.5 -pp "JC" --wlen-range "np.array([450,650])" --second-time-factor 1
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 6 --parallel True -res 2 --from-um-factor 10e-3 -s "Courant0.50Res2" -f "AuMieMediums/AllWaterTest/6)Courant/500to700" -r 51.5 -pp "R" --wlen-range "np.array([500,700])" --courant .5 --index 1.33
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 6 --parallel True -res 2 --from-um-factor 10e-3 -s "RefRRes2" -f "AuMieMediums/AllWaterTest/9)BoxDimensions/RefIdeal/3)NewRef" -r 51.5 -pp "R" --wlen-range "np.array([500,650])" --index 1.33
############
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 6 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyFalseNP6" -res 2 --split-chunks-evenly False --index 1.33 --wlen-range "[500, 650]"
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 6 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyTrueNP6" -res 2 --split-chunks-evenly True --index 1.33 --wlen-range "[500, 650]" --load-flux False
#mpirun --use-hwthread-cpus -np 3 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 3 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyFalseNP3" -res 2 --split-chunks-evenly False --index 1.33 --wlen-range "[500, 650]"
#mpirun --use-hwthread-cpus -np 3 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 3 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyTrueNP3" -res 2 --split-chunks-evenly True --index 1.33 --wlen-range "[500, 650]"
#mpirun --use-hwthread-cpus -np 4 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 4 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyFalseNP4" -res 2 --split-chunks-evenly False --index 1.33 --wlen-range "[500, 650]"
#mpirun --use-hwthread-cpus -np 4 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 4 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyTrueNP4" -res 2 --split-chunks-evenly True --index 1.33 --wlen-range "[500, 650]"
#mpirun --use-hwthread-cpus -np 5 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 5 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyFalseNP5" -res 2 --split-chunks-evenly False --index 1.33 --wlen-range "[500, 650]"
#mpirun --use-hwthread-cpus -np 5 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 5 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyTrueNP5" -res 2 --split-chunks-evenly True --index 1.33 --wlen-range "[500, 650]"
#mpirun --use-hwthread-cpus -np 2 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 2 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyFalseNP2" -res 2 --split-chunks-evenly False --index 1.33 --wlen-range "[500, 650]"
#mpirun --use-hwthread-cpus -np 2 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 2 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyTrueNP2" -res 2 --split-chunks-evenly True --index 1.33 --wlen-range "[500, 650]"
#mpirun --use-hwthread-cpus -np 1 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 1 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyFalseNP1" -res 2 --split-chunks-evenly False --index 1.33 --wlen-range "[500, 650]"
#mpirun --use-hwthread-cpus -np 1 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 1 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyTrueNP1" -res 2 --split-chunks-evenly True --index 1.33 --wlen-range "[500, 650]"
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 6 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyFalseNP6" -res 2 --split-chunks-evenly False --wlen-range "[450, 600]"
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 6 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyTrueNP6" -res 2 --split-chunks-evenly True --wlen-range "[450, 600]" --load-flux False
#mpirun --use-hwthread-cpus -np 3 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 3 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyFalseNP3" -res 2 --split-chunks-evenly False --wlen-range "[450, 600]"
#mpirun --use-hwthread-cpus -np 3 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 3 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyTrueNP3" -res 2 --split-chunks-evenly True --wlen-range "[450, 600]"
#mpirun --use-hwthread-cpus -np 4 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 4 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyFalseNP4" -res 2 --split-chunks-evenly False --wlen-range "[450, 600]"
#mpirun --use-hwthread-cpus -np 4 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 4 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyTrueNP4" -res 2 --split-chunks-evenly True --wlen-range "[450, 600]"
#mpirun --use-hwthread-cpus -np 5 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 5 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyFalseNP5" -res 2 --split-chunks-evenly False --wlen-range "[450, 600]"
#mpirun --use-hwthread-cpus -np 5 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 5 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyTrueNP5" -res 2 --split-chunks-evenly True --wlen-range "[450, 600]"
#mpirun --use-hwthread-cpus -np 2 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 2 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyFalseNP2" -res 2 --split-chunks-evenly False --wlen-range "[450, 600]"
#mpirun --use-hwthread-cpus -np 2 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 2 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyTrueNP2" -res 2 --split-chunks-evenly True --wlen-range "[450, 600]"
#mpirun --use-hwthread-cpus -np 1 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 1 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyFalseNP1" -res 2 --split-chunks-evenly False --wlen-range "[450, 600]"
#mpirun --use-hwthread-cpus -np 1 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 1 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyTrueNP1" -res 2 --split-chunks-evenly True --wlen-range "[450, 600]"
###########
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 6 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyFalseNP6" -res 4 --split-chunks-evenly False --index 1.33 --wlen-range "[500, 650]"
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 6 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyTrueNP6" -res 4 --split-chunks-evenly True --index 1.33 --wlen-range "[500, 650]"
#mpirun --use-hwthread-cpus -np 3 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 3 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyFalseNP3" -res 4 --split-chunks-evenly False --index 1.33 --wlen-range "[500, 650]"
#mpirun --use-hwthread-cpus -np 3 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 3 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyTrueNP3" -res 4 --split-chunks-evenly True --index 1.33 --wlen-range "[500, 650]"
mpirun --use-hwthread-cpus -np 4 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 4 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyFalseNP4" -res 4 --split-chunks-evenly False --index 1.33 --wlen-range "[500, 650]" --load-chunks False
mpirun --use-hwthread-cpus -np 4 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 4 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyTrueNP4" -res 4 --split-chunks-evenly True --index 1.33 --wlen-range "[500, 650]"
#mpirun --use-hwthread-cpus -np 5 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 5 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyFalseNP5" -res 4 --split-chunks-evenly False --index 1.33 --wlen-range "[500, 650]"
#mpirun --use-hwthread-cpus -np 5 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 5 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyTrueNP5" -res 4 --split-chunks-evenly True --index 1.33 --wlen-range "[500, 650]"
#mpirun --use-hwthread-cpus -np 2 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 2 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyFalseNP2" -res 4 --split-chunks-evenly False --index 1.33 --wlen-range "[500, 650]"
#mpirun --use-hwthread-cpus -np 2 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 2 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyTrueNP2" -res 4 --split-chunks-evenly True --index 1.33 --wlen-range "[500, 650]"
#mpirun --use-hwthread-cpus -np 1 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 1 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyFalseNP1" -res 4 --split-chunks-evenly False --index 1.33 --wlen-range "[500, 650]"
#mpirun --use-hwthread-cpus -np 1 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 1 --parallel True -f "Test/TestChunks" -s "AllWatChunksEvenlyTrueNP1" -res 4 --split-chunks-evenly True --index 1.33 --wlen-range "[500, 650]"
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 6 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyFalseNP6" -res 4 --split-chunks-evenly False --wlen-range "[450, 600]"
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 6 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyTrueNP6" -res 4 --split-chunks-evenly True --wlen-range "[450, 600]"
#mpirun --use-hwthread-cpus -np 3 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 3 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyFalseNP3" -res 4 --split-chunks-evenly False --wlen-range "[450, 600]"
#mpirun --use-hwthread-cpus -np 3 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 3 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyTrueNP3" -res 4 --split-chunks-evenly True --wlen-range "[450, 600]"
#mpirun --use-hwthread-cpus -np 4 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 4 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyFalseNP4" -res 4 --split-chunks-evenly False --wlen-range "[450, 600]"
#mpirun --use-hwthread-cpus -np 4 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 4 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyTrueNP4" -res 4 --split-chunks-evenly True --wlen-range "[450, 600]"
#mpirun --use-hwthread-cpus -np 5 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 5 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyFalseNP5" -res 4 --split-chunks-evenly False --wlen-range "[450, 600]"
#mpirun --use-hwthread-cpus -np 5 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 5 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyTrueNP5" -res 4 --split-chunks-evenly True --wlen-range "[450, 600]"
#mpirun --use-hwthread-cpus -np 2 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 2 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyFalseNP2" -res 4 --split-chunks-evenly False --wlen-range "[450, 600]"
#mpirun --use-hwthread-cpus -np 2 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 2 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyTrueNP2" -res 4 --split-chunks-evenly True --wlen-range "[450, 600]"
#mpirun --use-hwthread-cpus -np 1 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 1 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyFalseNP1" -res 4 --split-chunks-evenly False --wlen-range "[450, 600]"
#mpirun --use-hwthread-cpus -np 1 python -m mpi4py ../AuMieSphere/u_au_mie_scattering.py -np 1 --parallel True -f "Test/TestChunks" -s "AllVacChunksEvenlyTrueNP1" -res 4 --split-chunks-evenly True --wlen-range "[450, 600]"
