# Prueba de períodos
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave" -s "TestPeriods" --time-period-factor 30

# Prueba de grosor PML
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/PMLwlen/Vacuum" -s "PMLwlen0.40" --pml-wlen-factor 0.4 --centered-source False --index 1 --wlen-in-vacuum True
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/PMLwlen/Vacuum" -s "PMLwlen0.42" --pml-wlen-factor 0.42 --centered-source False --index 1 --wlen-in-vacuum True
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/PMLwlen/Vacuum" -s "PMLwlen0.44" --pml-wlen-factor 0.44 --centered-source False --index 1 --wlen-in-vacuum True
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/PMLwlen/Vacuum" -s "PMLwlen0.46" --pml-wlen-factor 0.46 --centered-source False --index 1 --wlen-in-vacuum True
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/PMLwlen/Vacuum" -s "PMLwlen0.36" --pml-wlen-factor 0.36 --centered-source False --index 1 --wlen-in-vacuum True
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/PMLwlen/Vacuum" -s "PMLwlen0.34" --pml-wlen-factor 0.34 --centered-source False --index 1 --wlen-in-vacuum True
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/PMLwlen/Vacuum" -s "PMLwlen0.32" --pml-wlen-factor 0.32 --centered-source False --index 1 --wlen-in-vacuum True
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/PMLwlen/Vacuum" -s "PMLwlen0.30" --pml-wlen-factor 0.3 --centered-source False --index 1 --wlen-in-vacuum True
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/PMLwlen/Vacuum" -s "PMLwlen0.25" --pml-wlen-factor 0.25 --centered-source False --index 1 --wlen-in-vacuum True
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/PMLwlen/Vacuum" -s "PMLwlen0.50" --pml-wlen-factor 0.5 --centered-source False --index 1 --wlen-in-vacuum True
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/PMLwlen/Vacuum" -s "PMLwlen0.20" --pml-wlen-factor 0.2  --centered-source False --index 1 --wlen-in-vacuum True
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/PMLwlen/Vacuum" -s "PMLwlen0.55" --pml-wlen-factor 0.55 --centered-source False --index 1 --wlen-in-vacuum True
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/PMLwlen/Vacuum" -s "PMLwlen0.10" --pml-wlen-factor 0.1 --centered-source False --index 1 --wlen-in-vacuum True
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/PMLwlen/Vacuum" -s "PMLwlen0.05" --pml-wlen-factor 0.05 --centered-source False --index 1 --wlen-in-vacuum True
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/PMLwlen/Vacuum" -s "PMLwlen0.01" --pml-wlen-factor 0.01 --centered-source False --index 1 --wlen-in-vacuum True
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/PMLwlen/Vacuum" -s "PMLwlen0.15" --pml-wlen-factor 0.15 --centered-source False --index 1 --wlen-in-vacuum True
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/PMLwlen/Vacuum" -s "PMLwlen0.60" --pml-wlen-factor 0.6 --centered-source False --index 1 --wlen-in-vacuum True
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/PMLwlen/Vacuum" -s "PMLwlen0.12" --pml-wlen-factor 0.12 --centered-source False --index 1 --wlen-in-vacuum True
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/PMLwlen/Vacuum" -s "PMLwlen0.17" --pml-wlen-factor 0.17 --centered-source False --index 1 --wlen-in-vacuum True
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/PMLwlen/Vacuum" -s "PMLwlen0.22" --pml-wlen-factor 0.22 --centered-source False --index 1 --wlen-in-vacuum True
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/PMLwlen/Vacuum" -s "PMLwlen0.27" --pml-wlen-factor 0.27 --centered-source False --index 1 --wlen-in-vacuum True
#mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/PMLwlen/Vacuum" -s "PMLwlen0.38" --pml-wlen-factor 0.38 --centered-source False --index 1 --wlen-in-vacuum True

# Test resolution
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 10 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen10"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 20 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen20"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 30 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen30"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 40 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen40"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 50 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen50"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 60 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen60"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 70 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen70"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 80 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen80"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 90 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen90"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen100"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 130 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen130"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 150 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen150"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 170 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen170"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 200 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen200"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 15 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen15"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 5 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen05"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 8 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen08"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 3 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen03"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 240 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen240"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 280 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen280"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 320 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen320"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 300 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen300"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 260 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen260"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 220 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Vacuum" --centered-source False --index 1 --wlen-in-vacuum True -s "ResWlen220"

mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 10 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen10"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 20 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen20"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 30 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen30"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 40 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen40"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 50 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen50"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 60 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen60"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 70 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen70"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 80 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen80"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 90 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen90"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen100"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 130 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen130"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 150 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen150"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 170 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen170"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 200 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen200"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 15 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen15"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 5 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen05"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 8 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen08"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 3 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen03"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 240 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen240"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 280 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen280"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 320 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen320"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 300 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen300"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 260 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen260"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 220 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/Water" --centered-source False --index 1.33 --wlen-in-vacuum True -s "ResWlen220"

mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 10 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen10"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 20 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen20"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 30 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen30"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 40 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen40"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 50 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen50"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 60 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen60"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 70 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen70"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 80 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen80"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 90 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen90"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 100 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen100"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 130 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen130"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 150 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen150"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 170 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen170"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 200 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen200"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 15 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen15"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 5 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen05"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 8 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen08"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 3 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen03"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 240 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen240"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 280 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen280"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 320 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen320"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 300 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen300"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 260 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen260"
mpirun -np 4 python -m mpi4py Sources/u_monoch_field.py --resolution-wlen 220 --empty-wlen-factor .5 -f "Field/Sources/MonochPlanewave/TestNoRoundUp/Res/WLenInMedium/Water" --centered-source False --index 1.33 --wlen-in-vacuum False -s "ResWlen220"
