#!/bin/bash

mpirun --use-hwthread-cpus -np 6 python -m mpi4py n_au_mie_scattering.py -np 6 --parallel True -res 1 -s "TestPaperJCFitRes1" -f "AuMieSphere/AuMie/13)TestPaper/4)PaperJCFit/TestPaperJCFit103MaxRes" -r 51.5 -pp "JC" --wlen-range "np.array([500,650])" --from-um-factor 20e-3
mpirun --use-hwthread-cpus -np 6 python -m mpi4py n_au_mie_scattering.py -np 6 --parallel True -res 2 -s "TestPaperJCFitRes2" -f "AuMieSphere/AuMie/13)TestPaper/4)PaperJCFit/TestPaperJCFit103MaxRes" -r 51.5 -pp "JC" --wlen-range "np.array([500,650])" --from-um-factor 20e-3
mpirun --use-hwthread-cpus -np 6 python -m mpi4py n_au_mie_scattering.py -np 6 --parallel True -res 3 -s "TestPaperJCFitRes3" -f "AuMieSphere/AuMie/13)TestPaper/4)PaperJCFit/TestPaperJCFit103MaxRes" -r 51.5 -pp "JC" --wlen-range "np.array([500,650])" --from-um-factor 20e-3
mpirun --use-hwthread-cpus -np 6 python -m mpi4py n_au_mie_scattering.py -np 6 --parallel True -res 4 -s "TestPaperJCFitRes4" -f "AuMieSphere/AuMie/13)TestPaper/4)PaperJCFit/TestPaperJCFit103MaxRes" -r 51.5 -pp "JC" --wlen-range "np.array([500,650])" --from-um-factor 20e-3
mpirun --use-hwthread-cpus -np 6 python -m mpi4py n_au_mie_scattering.py -np 6 --parallel True -res 5 -s "TestPaperJCFitRes5" -f "AuMieSphere/AuMie/13)TestPaper/4)PaperJCFit/TestPaperJCFit103MaxRes" -r 51.5 -pp "JC" --wlen-range "np.array([500,650])" --from-um-factor 20e-3
mpirun --use-hwthread-cpus -np 6 python -m mpi4py n_au_mie_scattering.py -np 6 --parallel True -res 6 -s "TestPaperJCFitRes6" -f "AuMieSphere/AuMie/13)TestPaper/4)PaperJCFit/TestPaperJCFit103MaxRes" -r 51.5 -pp "JC" --wlen-range "np.array([500,650])" --from-um-factor 20e-3
mpirun --use-hwthread-cpus -np 6 python -m mpi4py n_au_mie_scattering.py -np 6 --parallel True -res 7 -s "TestPaperJCFitRes7" -f "AuMieSphere/AuMie/13)TestPaper/4)PaperJCFit/TestPaperJCFit103MaxRes" -r 51.5 -pp "JC" --wlen-range "np.array([500,650])" --from-um-factor 20e-3
mpirun --use-hwthread-cpus -np 6 python -m mpi4py n_au_mie_scattering.py -np 6 --parallel True -res 8 -s "TestPaperJCFitRes8" -f "AuMieSphere/AuMie/13)TestPaper/4)PaperJCFit/TestPaperJCFit103MaxRes" -r 51.5 -pp "JC" --wlen-range "np.array([500,650])" --from-um-factor 20e-3
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py n_au_mie_scattering.py -np 6 --parallel True -res 9 -s "TestPaperJCFitRes9" -f "AuMieSphere/AuMie/13)TestPaper/4)PaperJCFit/TestPaperJCFit103MaxRes" -r 51.5 -pp "JC" --wlen-range "np.array([500,650])" --from-um-factor 20e-3
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py n_au_mie_scattering.py -np 6 --parallel True -res 10 -s "TestPaperJCFitRes10" -f "AuMieSphere/AuMie/13)TestPaper/4)PaperJCFit/TestPaperJCFit103MaxRes" -r 51.5 -pp "JC" --wlen-range "np.array([500,650])" --from-um-factor 20e-3
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py n_au_mie_scattering.py -np 6 --parallel True -res 11 -s "TestPaperJCFitRes11" -f "AuMieSphere/AuMie/13)TestPaper/4)PaperJCFit/TestPaperJCFit103MaxRes" -r 51.5 -pp "JC" --wlen-range "np.array([500,650])" --from-um-factor 20e-3
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py n_au_mie_scattering.py -np 6 --parallel True -res 11 -s "TestPaperJCFitRes11" -f "AuMieSphere/AuMie/13)TestPaper/4)PaperJCFit/TestPaperJCFit103MaxRes" -r 51.5 -pp "JC" --wlen-range "np.array([500,650])" --from-um-factor 20e-3
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py n_au_mie_scattering.py -np 6 --parallel True -res 12 -s "TestPaperJCFitRes12" -f "AuMieSphere/AuMie/13)TestPaper/4)PaperJCFit/TestPaperJCFit103MaxRes" -r 51.5 -pp "JC" --wlen-range "np.array([500,650])" --from-um-factor 20e-3
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py n_au_mie_scattering.py -np 6 --parallel True -res 13 -s "TestPaperJCFitRes13" -f "AuMieSphere/AuMie/13)TestPaper/4)PaperJCFit/TestPaperJCFit103MaxRes" -r 51.5 -pp "JC" --wlen-range "np.array([500,650])" --from-um-factor 20e-3
#mpirun --use-hwthread-cpus -np 6 python -m mpi4py n_au_mie_scattering.py -np 6 --parallel True -res 14 -s "TestPaperJCFitRes14" -f "AuMieSphere/AuMie/13)TestPaper/4)PaperJCFit/TestPaperJCFit103MaxRes" -r 51.5 -pp "JC" --wlen-range "np.array([500,650])" --from-um-factor 20e-3
