#!/bin/bash

# SLURM script to make intra-node test with the 103 nm gold nanosphere in visible spectrum

#SBATCH --ntasks=64                # Total number of cores

#SBATCH --nodes=1                  # Total number of nodes

#SBATCH -p free-rider              # Partition

#SBATCH -t 360                     # Maximum time reserved for execution, expressed in minutes

#SBATCH --job-name=au-mie-1-node                             # Task name

#SBATCH --output=SlurmScripts/ErrorLogs/au-mie-1-node-%j.out # Output file

#SBATCH --error=SlurmScripts/ErrorLogs/au-mie-1-node-%j.err  # Error file

# #SBATCH --test-only   # Check if legible and return posible start time

# Execute!
export PATH=/nfs/home/vpais/miniconda/bin:$PATH
conda init bash
source ~/.bash_profile
source ~/.bashrc
conda activate pmp
cd /nfs/home/vpais/ThesisPython

# Generate Machinefile for mpi such that hosts are in the same order as if run via srun
MACHINEFILE="SlurmScripts/ConfigFiles/nodes.$SLURM_JOB_ID"
srun -l /bin/hostname | sort -n | awk '{print $2}' > $MACHINEFILE

# Run using generated Machine file:
# mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE mpi-app
SLURM_NTASKS=64

# Test 1 node splitting evenly. Must find a problem that takes approximately 1 hour.
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 2 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes2" --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 4 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes4" --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 8 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes8" --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 16 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes16" --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 32 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes32" --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 64 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes64" --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 128 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes128" --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 256 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes256" --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 512 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes512" --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 1024 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes1024" --load-flux False
 
# Test 1 node in my classical resolutions. This should go at lightspeed in comparison.
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 2 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes2" --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 3 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes3" --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 4 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes4" --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 5 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes5" --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 6 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes6" --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 7 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes7" --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 8 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes8" --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 9 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes9" --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 10 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes10" --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 11 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes11" --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 12 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes12" --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 13 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes13" --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 14 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes14" --load-flux False

# Test 1 node in my classical resolutions but splitting by load. This should go at lightspeed in comparison.
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 2 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes2" --split-chunks-evenly False --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 3 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes3" --split-chunks-evenly False --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 4 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes4" --split-chunks-evenly False --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 5 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes5" --split-chunks-evenly False --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 6 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes6" --split-chunks-evenly False --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 7 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes7" --split-chunks-evenly False --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 8 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes8" --split-chunks-evenly False --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 9 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes9" --split-chunks-evenly False --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 10 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes10" --split-chunks-evenly False --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 11 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes11" --split-chunks-evenly False --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 12 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes12" --split-chunks-evenly False --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 13 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes13" --split-chunks-evenly False --load-flux False
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 14 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes14" --split-chunks-evenly False --load-flux False

# Test 1 node splitting evenly but at higher resolutions. Must find a problem that takes approximately 1 hour.
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 2048 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes2048"
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 4096 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes4096"
mpirun -np $SLURM_NTASKS -machinefile $MACHINEFILE python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc 64 -res 16384 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes16384"
