#!/bin/bash

# Script SLURM para scattering en esfera de oro

#SBATCH --ntasks=64     # Numero de cores totales para asignar al trabajo

#SBATCH --nodes=1       # Numero de nodos para asignar al trabajo

#SBATCH -p free-rider   # Partición a la que enviar el trabajo

#SBATCH -t 5            # Tiempo estimado (En minutos) para la ejecución
                        # de la tarea. Pasado ese tiempo, el slurm enviará
                        # la señal de terminación.

#SBATCH --job-name=au-mie-scatt      # Nombre de la tarea
#SBATCH --output=au-mie-scatt-%j.out # Archivo donde escribir la salida STDOUT
#SBATCH --error=au-mie-scatt-%j.err  # Archivo donde escribir la salida STDERR

# #SBATCH --test-only   # Ejemplo de linea comentada.
                        # El comando --test-only valida que el script sea legible
                        # por slurm y devuelve un estimado de cuando iniciaria
                        # su ejecución.

# Ejecucion de la aplicacion
# srun mpi-test

srun /nfs/home/vpais/ThesisPython/AuMieSphere/au-mie-scatt.sh
