#!/bin/bash

# SLURM script to make intra-node test with the 103 nm gold nanosphere in visible spectrum

#SBATCH --ntasks=64                # Total number of cores

#SBATCH --nodes=1                  # Total number of nodes

#SBATCH -p free-rider              # Partition

#SBATCH -t 360                     # Maximum time reserved for execution, expressed in minutes

#SBATCH --job-name=au-mie-1-node                             # Task name

#SBATCH --output="ErrorLogs/au-mie-1-node-%j.out" # Output file

#SBATCH --error="ErrorLogs/au-mie-1-node-%j.err"  # Error file

# #SBATCH --test-only   # Check if legible and return posible start time

# Execute!
export PATH=/nfs/home/vpais/miniconda/bin:$PATH
conda init bash
source ~/.bash_profile
source ~/.bashrc
conda activate pmp
cd /nfs/home/vpais/ThesisPython

alias tupacrun='srun -n $SLURM_NTASKS --mpi=pmi2 python -m mpi4py ./AuMieSphere/u_au_mie_scattering.py -nc $SLURM_NTASKS'

# Test 1 node splitting evenly. Must find a problem that takes approximately 1 hour.
# tupacrun -res 2 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes2" --load-flux False
# tupacrun -res 4 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes4" --load-flux False
tupacrun -res 8 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes8" --load-flux False
# tupacrun -res 16 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes16" --load-flux False
# tupacrun -res 32 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes32" --load-flux False
# tupacrun -res 64 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes64" --load-flux False
# tupacrun -res 128 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes128" --load-flux False
# tupacrun -res 256 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes256" --load-flux False
# tupacrun -res 512 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes512" --load-flux False
# tupacrun -res 1024 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes1024" --load-flux False
 
# Test 1 node in my classical resolutions. This should go at lightspeed in comparison.
# tupacrun -res 2 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes2" --load-flux False
# tupacrun -res 3 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes3" --load-flux False
# tupacrun -res 4 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes4" --load-flux False
# tupacrun -res 5 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes5" --load-flux False
# tupacrun -res 6 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes6" --load-flux False
# tupacrun -res 7 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes7" --load-flux False
# tupacrun -res 8 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes8" --load-flux False
# tupacrun -res 9 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes9" --load-flux False
# tupacrun -res 10 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes10" --load-flux False
# tupacrun -res 11 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes11" --load-flux False
# tupacrun -res 12 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes12" --load-flux False
# tupacrun -res 13 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes13" --load-flux False
# tupacrun -res 14 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitTrueRes" -s "1NodeRes14" --load-flux False

# Test 1 node in my classical resolutions but splitting by load. This should go at lightspeed in comparison.
# tupacrun -res 2 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes2" --split-chunks-evenly False --load-flux False
# tupacrun -res 3 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes3" --split-chunks-evenly False --load-flux False
# tupacrun -res 4 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes4" --split-chunks-evenly False --load-flux False
# tupacrun -res 5 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes5" --split-chunks-evenly False --load-flux False
# tupacrun -res 6 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes6" --split-chunks-evenly False --load-flux False
# tupacrun -res 7 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes7" --split-chunks-evenly False --load-flux False
# tupacrun -res 8 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes8" --split-chunks-evenly False --load-flux False
# tupacrun -res 9 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes9" --split-chunks-evenly False --load-flux False
# tupacrun -res 10 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes10" --split-chunks-evenly False --load-flux False
# tupacrun -res 11 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes11" --split-chunks-evenly False --load-flux False
# tupacrun -res 12 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes12" --split-chunks-evenly False --load-flux False
# tupacrun -res 13 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes13" --split-chunks-evenly False --load-flux False
# tupacrun -res 14 --from-um-factor 20e-3 -f "AuMieSphere/AuMie/15)TUPAC/1NodeSplitFalseRes" -s "1NodeRes14" --split-chunks-evenly False --load-flux False

# Test 1 node splitting evenly but at higher resolutions. Must find a problem that takes approximately 1 hour.
# tupacrun -res 2048 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes2048"
# tupacrun -res 4096 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes4096"
# tupacrun -res 16384 -f "AuMieSphere/AuMie/15)TUPAC/1NodeTest" -s "1NodeRes16384"
