#!/bin/bash

# Script SLURM para scattering en esfera de oro

#SBATCH --ntasks=64     # Numero de cores totales para asignar al trabajo

#SBATCH --nodes=1       # Numero de nodos para asignar al trabajo

#SBATCH -p free-rider   # Partición a la que enviar el trabajo

#SBATCH --job-name=au-mie-scattering      # Nombre de la tarea
#SBATCH --output=au-mie-scattering-%j.out # Archivo donde escribir la salida STDOUT
#SBATCH --error=au-mie-scattering-%j.err  # Archivo donde escribir la salida STDERR

# #SBATCH --test-only   # Ejemplo de linea comentada.
                        # El comando --test-only valida que el script sea legible
                        # por slurm y devuelve un estimado de cuando iniciaria
                        # su ejecución.

# Ejecucion de la aplicacion
# srun mpi-test

srun python -m mpi4py /nfs/home/vpais/ThesisPython/AuMieSphere/u_au_mie_scattering.py -np 64 --parallel True
